version: '3'

services:
  afilmory:
    build:
      context: .
      dockerfile: Dockerfile.nas
    container_name: afilmory
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./config:/config
      - /path/to/nas/photos:/photos
    environment:
      - CONFIG_PATH=/config/builder.config.json
      - TZ=Asia/Shanghai

volumes:
  config:
  photos: 